### ISSUE TITLE
Does this pipeline require root permission?

### ISSUE THREAD

**Issue by wangjianshou** [zifanzhu/MicroPro#1]
Does this pipeline require root permission?

**Comment by zifanzhu** [comment]
Hi wangjianshou,

Sorry for the late reply! 

Root permission is platform dependent. Since MicroPro requires a few dependencies, the installation of some of them might need root permission on your machine (or not). I encourage you to try the installation yourself and see how it goes. Let me know if you have any more questions.

Best,
Zifan

**Comment by wangjianshou** [comment]
Hi zifanzhu,
thank you for your reply firstly.
when running this pipeline, I get this error which generated by 'scripts/u_v_abund.R':
> File '4_virfinder/4_4_vf_summary/wc_vf_filtered' does not exist

'scripts/u_v_abund.R' belongs to 'rule unknown_v_abund'.

I confirmed that this file called 'wc_vf_filtered' does not exist, but I cannot find which step can gengrate it, could you give me some help or advice? thank you in advance.
Best,
wanjianshou

**Comment by zifanzhu** [comment]
Hi wanjianshou,

This is a bug fixed in the latest MicroPro. You may replace your 'snake-binning-P' file with the new one and run the Snakemake command again (without deleting old results). Snakemake will skip what you've obtained and run what you didn't get. Let me know if this solves your problem.

Best,
Zifan

**Comment by wangjianshou** [comment]
Hi,
thank you very much. 
It is already running successfully. But there is a small bug in this script called "scripts/u_v_abund.R":
> line 95: vp <- v_ctg / ctg

But both of `v_ctg` and `ctg` are instances  of data.table class. So I think this line should be `vp <- v_ctg[1,1] / ctg[1,1]`

Thank you
wangjianshou
